[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 