services:
  - type: web
    name: instagram-dm-bot
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: IG_VERIFY_TOKEN
        sync: false
      - key: IG_PAGE_TOKEN
        sync: false
      - key: IG_APP_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 5001 